### ISSUE TITLE
Path Handling Issues on Windows

### ISSUE THREAD

**Issue by Vadoola** [cooklang/cookcli#167]
I haven't spent a lot of time looking at this issues, so I don't know if it's a more general issue, or specific to this single instance where it occurred.

This is my first time trying cook lang, and doing some testing to see if it fits my purpose. I downloaded the CLI on a Windows machine, because that's what I happened to be in front of at that time (I plan to use it on Linux if it's works for me long term)

Machine
Windows 11 Pro Version 24H2

Steps to Reproduce

1. Download cook-x86_64-pc-windows-msvc. Edit: I tested this with v0.17.2, I haven't tried any previous version.
2. Unzip cook-x86_64-pc-windows-msvc
3. Open terminal in folder the program was unzipped to (I tried the below set of commands from the old dos cmd promt, Powershell, and Nushell, in case that changed anything)
4. Follow the "Getting Started" steps listed in the Readme
5. cook seed
6. cook recipe "Neapolitan Pizza.cook"
7. cook -v shopping-list "Neapolitan Pizza.cook"

Then I get the follow error each time.

> Error: Failed to find referenced recipe './Shared/Pizza Dough' from '\\?\C:\Users\John Smith\Downloads\cook-x86_64-pc-windows-msvc\Neapolitan Pizza.cook'
> 
> Caused by:
>     Invalid recipe path: Shared/Pizza Dough

While it looks like it was an issue with relative path handling, I know sometimes spaces in directories can cause issues for some software in Windows, so as a test, I copied the contents of the directory to c:\tmp\cook, and ran the test again.

> Error: Failed to find referenced recipe './Shared/Pizza Dough' from '\\?\C:\tmp\cook\Neapolitan Pizza.cook'
> 
> Caused by:
>     Invalid recipe path: Shared/Pizza Dough

So it points to some sort of issue with relative path handling. It's unclear to me if this is related to Issued #102 or not.

**Comment by sjsepan3** [comment]
This also seems to be the case in Linux:

```
ERROR Error processing recipe: Failed to find referenced recipe './Shared/Pizza Dough' from '/home/sjsepan/Projects/CookLang/Survival Cookbook/Neapolitan Pizza.cook'

```
In my case 'Shared' is a folder at the same level as the folder that is the root of the recipe book ('Survival Cookbook' which is just a name for my seeded folder) where the 'Neopolitan Pizza' recipe lives, so the relative path would seem to be accurate, but perhaps un-escaped spaces are involved(?)

```
      sjsepan    …/󰲋 /CookLang/Survival Cookbook      11:16    1 tree
.
├── 2 Day Plan.menu
├── Advanced
├── Basic
│   ├── Easy Pancakes.cook
│   ├── Easy Pancakes.jpg
│   └── Mexican Style Burrito.cook
├── config
│   ├── aisle.conf
│   └── pantry.conf
├── db
│   ├── eggs
│   │   ├── meta.yml
│   │   └── shopping.yml
│   ├── flour
│   │   └── shopping.yml
│   ├── milk
│   │   └── shopping.yml
│   ├── olive oil
│   │   └── shopping.yml
│   └── sea salt
│       └── shopping.yml
├── Neapolitan Pizza.cook
├── README.md
├── reports
│   ├── cost.md.jinja
│   ├── ingredients.md.jinja
│   └── recipe-card.md.jinja
├── Shared
│   ├── Guacamole.cook
│   ├── Pizza Dough.cook
│   └── Red Beans.cook
├── Sicilian-style Scottadito Lamb Chops.cook
├── Snack Basket I.cook
└── Snack Basket II.cook

12 directories, 23 files
      sjsepan    …/󰲋 /CookLang/Survival Cookbook      11:23    1

```

**Comment by dubadub** [comment]
Alright, seems like platform independent, I reproduced it on MacOS too. Strangely if I move file to a folder it works:

<img width="504" height="317" alt="Image" src="https://github.com/user-attachments/assets/d59218eb-93b9-4c8e-8df0-0e17803cd8cf" />

**Comment by Vadoola** [comment]
Interesting I wasn't sure of course, but thought perhaps it was an issue with handling spaces on Windows...clearly not.
Moving it to a sub-directory resolves the issue is more interesting, because it points to not being an issue  with handling an un-escaped space in the recipe name, since the space still exists in the recipe file name.

I was originally hoping I could look into this myself and issue a pull request, but I've been pretty swamped. If I do get a chance, and you are working on other things, I'm willing to look into this, but I may not get the chance any time soon.

**Comment by sjsepan3** [comment]
> Interesting I wasn't sure of course, but thought perhaps it was an issue with handling spaces on Windows...clearly not. Moving it to a sub-directory resolves the issue is more interesting, because it points to not being an issue with handling an un-escaped space in the recipe name, since the space still exists in the recipe file name.
> 
> I was originally hoping I could look into this myself and issue a pull request, but I've been pretty swamped. If I do get a chance, and you are working on other things, I'm willing to look into this, but I may not get the chance any time soon.

Agreed; it's not looking like the spaces after all...

**Comment by tr4cks** [comment]
There is the same error for a menu that references recipes. Depending on where the recipe is located, it throws an error. Typically in my case (on macOS), I cannot execute the menu located at the root of the seed.

**Comment by dubadub** [comment]
resolved

**Comment by tr4cks** [comment]
I still have the same kind of issue with menus that reference recipes in `v0.18.2`.

Tested with the `seed` on `mac os`:
```
$> cook --version                    
cookcli 0.18.2 - in food we trust

$> cook sl './2 Day Plan.menu'    
Error: Failed to find referenced recipe '/Sicilian-style Scottadito Lamb Chops' from '/Users/[...]/test/2 Day Plan.menu'

Caused by:
    Invalid recipe path: /Sicilian-style Scottadito Lamb Chops
```

**Comment by mawo66** [comment]
The problem seems to be src/util/mod.rs:181:

```rust
let ref_path = reference.path(std::path::MAIN_SEPARATOR_STR);
```

If reference.components is empty (only filename without directories prefixed) the path() function adds a single separator (e.g. "\\") in front of the filename, which makes this "local" filename invalid. A solution would be (like already done in doctor.rs):

```rust
let ref_path = if reference.components.is_empty() {
    reference.name.clone()
} else {
    reference.path(std::path::MAIN_SEPARATOR_STR)
};
```

But maybe it's better to change the path() function (in cooklang-rs repo) directly to:

```rust
impl RecipeReference {
    pub fn path(&self, separator: &str) -> String {
        if self.components.is_empty() {
            self.name.clone()
        } else {
            self.components.join(separator) + separator + &self.name
        }
    }
}
```

What do you think?

**Comment by dubadub** [comment]
Agree that we should change in parser. I think components should contain "." as one of elements. Then everything should work

**Comment by mawo66** [comment]
Yes, that should also do it. Needs changing the parse_reference() function. It should support only relative paths, I guess? I saw, that '../' (upper directory) may not be handled correctly. I will have a look at it and make a suggestion via PR, ok?

**Comment by dubadub** [comment]
That would be great, thank you! We can add support for two dots if you think it's easy.
